main/urls.py
from django.urls import path
from main.views import show_main, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, delete_item_ajax, add_amount_ajax, remove_amount_ajax, get_item_json, add_item_ajax, create_product_flutter, show_json_user

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('add/', add_amount_ajax, name='add'),
    path('remove/', remove_amount_ajax, name='remove'),
    path('delete/', delete_item_ajax, name='delete'), 
    path('get-item/', get_item_json, name='get_item_json'),
    path('create-ajax/', add_item_ajax, name='add_item_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    path("json-item/<str:uname>/",show_json_user, name="show_json_user"),
]

toko_pbp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    amount = models.IntegerField()
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "price", "amount", "description"]

main/views.py
import datetime
import json

from django.http import HttpResponseRedirect, Http404, HttpResponseNotFound
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponseRedirect, JsonResponse
from main.forms import ItemForm
from django.http import HttpResponse
from django.core import serializers
from django.urls import reverse
from main.models import Item
from django.contrib import messages
from django.db.models import Sum
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user) 

    context = {
        'app_name': 'main',
        'username': request.user.username,
        'class': 'PBP C',
        'items': items,
        'last_login': request.COOKIES.get('last_login'),
    }

    return render(request, "main.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
        else:
            messages.error(request, "Your username or password aren't valid!")
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def get_item_json(request):
  Items = Item.objects.filter(user=request.user)
  return HttpResponse(serializers.serialize('json', Items))

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_item = Item(name=name, price=price, amount=amount, description=description, user=user)
        new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_item_ajax(request):
    data = json.loads(request.body.decode("utf-8"))
    item = Item.objects.get(pk=data["id"])
    item.delete()
    return HttpResponse("DELETED",status=200)

@csrf_exempt
def add_amount_ajax(request):
    data = json.loads(request.body.decode("utf-8"))
    item = Item.objects.get(pk=data["id"])
    item.amount += 1
    item.save()
    return HttpResponse(status=200)

@csrf_exempt
def remove_amount_ajax(request):
    data = json.loads(request.body.decode("utf-8"))
    item = Item.objects.get(pk=data["id"])
    if item.amount > 1:
        item.amount -= 1
        item.save()
    return HttpResponse(status=200)

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
def show_json_user(request, username):
    data_item = Item.objects.all()
    for data in data_item:
        if data.user.username == username:
            user_id = data.user
            data = Item.objects.filter(user = user_id)
            break
        else:
            data = []
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

main/templates/login.html
{% extends 'base.html' %}

<head>
    {% block meta %}
        <title>Login</title>
    {% endblock meta %}
</head>

<body>
    {% block content %}
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family:'Arial', sans-serif;
        }

        body {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            background: #e7a180;
        }

        .container {
            width: 100%;
            display: flex;
            max-width: 400px;
            background: #fff;
            border-radius: 15px;
            box-shadow: 0 10px 15px rgba(0, 0, 0, 0.1);
        }

        .login {
            width: 400px;
        }

        form {
            width: 250px;
            margin: 60px auto;
        }

        h1 {
            margin: 20px;
            text-align: center;
            font-weight: bolder;
            text-transform: uppercase;
        }

        hr {
            border-top: 2px solid #e7a1b0;
        }

        p {
            text-align: center;
            margin: 10px;
        }

        form label {
            display: block;
            font-size: 16px;
            font-weight: 600;
            padding: 5px;
        }

        input {
            width: 100%;
            margin: 2px;
            border: none;
            outline: none;
            padding: 8px;
            border-radius: 5px;
            border: 1px solid gray;
        }

        button {
            border: none;
            outline: none;
            padding: 8px;
            width: 252px;
            color: #fff;
            font-size: 16px;
            cursor: pointer;
            margin-top: 20px;
            border-radius: 5px;
            background: #d5647c;
        }

        button:hover {
            background: rgba(231, 161, 176, 1);
        }


        @media (max-width: 880px) {
            .container {
                width: 100%;
                max-width: 400px;
                margin-left: 20px;
                margin-right: 20px;
            }

            form {
                width: 300px;
                margin: 20px auto;
            }

            .login {
                width: 400px;
                padding: 20px;
            }

            button {
                width: 100%;
            }
        }

    </style>
    
    <div class="container">
        <div class = "login">

            <form method="POST" action="">
                <h1>Login</h1>
                {% csrf_token %}
                <label for="">Username</label>
                <input type="text" name="username" placeholder="Username" class="form-control">
                <label for="">Password</label>
                <input type="password" name="password" placeholder="Password" class="form-control">
                <button type="submit">Login</button>

                {% if messages %}
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %} 
                <br>
               <p>Don't have an account yet?
                <a href="{% url 'main:register' %}">Register Now</a>
               </p>
            </form>
        </div>
    </div>
    {% endblock content %}
</body>

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: sans-serif;
    }

    body {
        height: 100vh;
        background: #e7a180;
    }

    nav {
        position: absolute;
        background: #ffffff;
        top: 0;
        left: 0;
        padding: 0 80px;
        width: 100%;
        box-sizing: border-box;
    }

    header, #amount-message {
        margin: 20px 0;
        padding: 0 50px;
        text-align: center;
    }

    footer {
        margin-top: 20px;
        padding: 0 50px;
        text-align: center;
    }

    .product {
        display: flex;
        flex-wrap: wrap;
        justify-content: flex-start;
        padding: 0 50px;
    }

    .card {
        width: 250px;
        flex: 0 0 calc(33.33% - 20px);
        background: #fff;
        margin-bottom: 20px; /* Jarak antara kartu */
        margin-right: 20px;
    }

    .card:last-child, .card:last-child .flex-v {
        background: #1569C7;
    }

    .primary-button,
    .secondary-button,
    .btn-outline-success {
        border: none;
        outline: none;
        padding: 8px;
        color: #fff;
        font-size: 16px;
        cursor: pointer;
        border-radius: 5px;
        text-align: center; /* Mengatur teks ke tengah tombol */
    }

    button:hover {
        background: rgba(231, 161, 176, 1);
    }

    .primary-button {
        width: 100%;
        background: #d5647c;
    }

    .secondary-button {
        width: 15x;
        background: #d5647c;
    }

    .btn-outline-success {
        color: #d5647c;
        outline-color: #d5647c;
        background-color: #fff;
    }

    #btn_add_item {
        width: 200px;
    }

    .btn-outline-success:hover {
        border-color: #d5647c;
        background: rgba(231, 161, 176, 1);
    }

    .flex-v {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

</style>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"><h3 style="font-family: 'Lucida bright';">TOKO PBP SABRINA</h3></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            </ul>
            <a href="{% url 'main:logout' %}">
                <button class="btn btn-outline-success" type="submit">Logout</button>
            </a>
        </div>
    </div>
</nav>

<body>
    <header>
        <h2 style="font-family: 'Lucida bright';">Halo, {{ username }}!</h2>
        <p>Sesi terakhir login: {{ last_login }}</p>
    </header>

    <div id="amount-message">
    </div>

    <div class="product" id="product">
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="price" class="col-form-label">Price:</label>
                            <input type="number" class="form-control" id="price" name="price"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                </div>
            </div>
        </div>
    </div>

    <footer>
        <button type="button" class="btn btn-outline-success" id="btn_add_item" data-bs-toggle="modal" data-bs-target="#exampleModal" style="margin: 20px;">Add New Item</button>
    </footer>
</body>

<script>
async function getItems() {
    return fetch("{% url 'main:get_item_json' %}").then((res) => res.json())
}
async function refreshItems() {
    const items = await getItems()
    const jumlahItem = items.length
    let htmlString1 = `<h4>Kamu menyimpan ${jumlahItem} item pada aplikasi ini</h4>`
    let htmlString2 = ""
    items.forEach((item) => {
        console.log(item)
        htmlString2 +=
        `<div class="card">
            <div class="card-body">
                <h5 class="card-title">${item.fields.name}</h5>
                <p class="card-text">${item.fields.description}</p>
                <p class="card-text">Price: Rp${item.fields.price}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item flex-v">Amount: ${item.fields.amount}
                    <div>
                        <button value="${item.pk}" onclick="addAmount(${item.pk})" class="secondary-button">Add</button>
                        <button value="${item.pk}" onclick="removeAmount(${item.pk})" class="secondary-button">Remove</button>
                    </div>
                </li>
            </ul>
            <div class="card-body">
                <button value="${item.pk}" onclick="deleteItem(${item.pk})" class="primary-button">Delete</button>
            </div>
        </div>` 
    })
    document.getElementById("amount-message").innerHTML = htmlString1
    document.getElementById("product").innerHTML = htmlString2
}

refreshItems()

function addItem() {
    fetch("{% url 'main:add_item_ajax' %}", {
        method: "POST",
        body: new FormData(document.querySelector('#form'))
    }).then(refreshItems)

    document.getElementById("form").reset()
    return false
}

document.getElementById("button_add").onclick = addItem

function deleteItem(id) {
  fetch(`/delete/`, {
    method: "DELETE",
    body: JSON.stringify({
      id: id
    }),
    headers: {
      'Content-type': 'application/json; charset=UTF-8',
    },
  }).then(res => {
    refreshItems();
  }).catch(err => {
    console.log(err);
    alert("Gagal menghapus item.");
  })
}

function addAmount(id) {
  fetch(`/add/`, {
    method: "PATCH",
    body: JSON.stringify({
      id: id
    }),
    headers: {
      'Content-type': 'application/json; charset=UTF-8',
    },
  }).then(res => {
    refreshItems();
  }).catch(err => {
    console.log(err);
    alert("Gagal menambah amount item.");
  })
}

function removeAmount(id) {
  fetch(`/remove/`, {
    method: "PATCH",
    body: JSON.stringify({
      id: id
    }),
    headers: {
      'Content-type': 'application/json; charset=UTF-8',
    },
  }).then(res => {
    refreshItems();
  }).catch(err => {
    console.log(err);
    alert("Gagal mengurangi amount item.");
  })
}
</script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %} 
<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family:'Arial', sans-serif;
    }

    body {
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        background: #e7a180;
    }

    .container {
        width: 100%;
        display: flex;
        max-width: 400px;
        background: #fff;
        border-radius: 15px;
        box-shadow: 0 10px 15px rgba(0, 0, 0, 0.1);
    }

    .login {
        width: 400px;
    }

    form {
        width: 250px;
        margin: 60px auto;
    }

    h1 {
        margin: 20px;
        text-align: center;
        font-weight: bolder;
        text-transform: uppercase;
    }

    hr {
        border-top: 2px solid #e7a1b0;
    }

    p {
        text-align: center;
        margin: 10px;
    }

    form label {
        display: block;
        font-size: 16px;
        font-weight: 600;
        padding: 5px;
    }

    input {
        width: 100%;
        margin: 2px;
        border: none;
        outline: none;
        padding: 8px;
        border-radius: 5px;
        border: 1px solid gray;
    }

    button {
        border: none;
        outline: none;
        padding: 8px;
        width: 252px;
        color: #fff;
        font-size: 16px;
        cursor: pointer;
        margin-top: 20px;
        border-radius: 5px;
        background: #d5647c;
    }

    button:hover {
        background: rgba(231, 161, 176, 1);
    }


    @media (max-width: 880px) {
        .container {
            width: 100%;
            max-width: 400px;
            margin-left: 20px;
            margin-right: 20px;
        }

        form {
            width: 300px;
            margin: 20px auto;
        }

        .login {
            width: 400px;
            padding: 20px;
        }

        button {
            width: 100%;
        }
    } 

</style> 
<div class = "container"> 
    <div class = "login">  
        <form method="POST">
            <h1>Register</h1>  
            {% csrf_token %}  
            <label>{{form.username.label}}</label>
            {{form.username}}
            <label>{{form.password1.label}}</label>
            {{form.password1}}
            <label>{{form.password2.label}}</label>
            {{form.password2}}
            <button type="submit" name="submit">Daftar</button>
            {% if messages %}  
                <ul>   
                    {% for message in messages %}  
                        <li>{{ message }}</li>  
                        {% endfor %}  
                </ul>   
            {% endif %}
        </form>
    </div>
</div>  

{% endblock content %}